### ISSUE TITLE
Rencana Panel Kontrol

### ISSUE THREAD

**Issue by mdestafadilah** [kurniawandata/nasihosting#4]
Halo Mas Kur,

saya tertarik sekali dengan project nasihosting ini, apakah kedepannya ada penambahan Panel Kontrol untuk hostinganya, seperti CPANEL, berdasarkan lisensi yang dipakai oleh nasihosting, GPL V3, sepertinya **Vesta Panel** cocok untuk project nasihosting.

https://github.com/serghey-rodin/vesta

mungkin bisa dibantu kondisinya mas.

**Comment by benyaminl** [comment]
@mdestafadilah VestaCP already superseed by https://github.com/hestiacp/hestiacp, it's okay to use it on production, but there are a lot of bugs on it.

**Comment by mdestafadilah** [comment]
> @mdestafadilah VestaCP already superseed by https://github.com/hestiacp/hestiacp, it's okay to use it on production, but there are a lot of bugs on it.

hehe.. sekarang saya pakai aaPanel. banyak fiturenyah. hehe
